[2023-06-11 03:56:00,733] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 01_unscheduled.fetch_events manual__2023-06-11T03:54:24.205713+00:00 [queued]>
[2023-06-11 03:56:00,740] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 01_unscheduled.fetch_events manual__2023-06-11T03:54:24.205713+00:00 [queued]>
[2023-06-11 03:56:00,741] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-11 03:56:00,742] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-06-11 03:56:00,743] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-11 03:56:00,751] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): fetch_events> on 2023-06-11 03:54:24.205713+00:00
[2023-06-11 03:56:00,755] {standard_task_runner.py:52} INFO - Started process 547 to run task
[2023-06-11 03:56:00,758] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '01_unscheduled', 'fetch_events', 'manual__2023-06-11T03:54:24.205713+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/unscheduled.py', '--cfg-path', '/tmp/tmppyu4_4p2', '--error-file', '/tmp/tmp8q_mznm3']
[2023-06-11 03:56:00,760] {standard_task_runner.py:80} INFO - Job 70: Subtask fetch_events
[2023-06-11 03:56:00,805] {task_command.py:371} INFO - Running <TaskInstance: 01_unscheduled.fetch_events manual__2023-06-11T03:54:24.205713+00:00 [running]> on host fd847b0d0eb3
[2023-06-11 03:56:00,849] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=01_unscheduled
AIRFLOW_CTX_TASK_ID=fetch_events
AIRFLOW_CTX_EXECUTION_DATE=2023-06-11T03:54:24.205713+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-11T03:54:24.205713+00:00
[2023-06-11 03:56:00,851] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-11 03:56:00,852] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p /data/events && curl -o /data/events.json https://develop-park.tistory.com/rss']
[2023-06-11 03:56:00,861] {subprocess.py:85} INFO - Output:
[2023-06-11 03:56:00,863] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/data’: Permission denied
[2023-06-11 03:56:00,865] {subprocess.py:96} INFO - Command exited with return code 1
[2023-06-11 03:56:00,876] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-11 03:56:00,879] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=01_unscheduled, task_id=fetch_events, execution_date=20230611T035424, start_date=20230611T035600, end_date=20230611T035600
[2023-06-11 03:56:00,886] {standard_task_runner.py:97} ERROR - Failed to execute job 70 for task fetch_events (Bash command failed. The command returned a non-zero exit code 1.; 547)
[2023-06-11 03:56:00,934] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-11 03:56:00,958] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
