[2023-06-11 03:57:55,791] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 01_unscheduled.fetch_events manual__2023-06-11T03:54:24.205713+00:00 [queued]>
[2023-06-11 03:57:55,797] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 01_unscheduled.fetch_events manual__2023-06-11T03:54:24.205713+00:00 [queued]>
[2023-06-11 03:57:55,798] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-11 03:57:55,800] {taskinstance.py:1377} INFO - Starting attempt 3 of 3
[2023-06-11 03:57:55,801] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-11 03:57:55,808] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): fetch_events> on 2023-06-11 03:54:24.205713+00:00
[2023-06-11 03:57:55,812] {standard_task_runner.py:52} INFO - Started process 650 to run task
[2023-06-11 03:57:55,814] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '01_unscheduled', 'fetch_events', 'manual__2023-06-11T03:54:24.205713+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/unscheduled.py', '--cfg-path', '/tmp/tmpirkzyo8l', '--error-file', '/tmp/tmperwmmhw3']
[2023-06-11 03:57:55,816] {standard_task_runner.py:80} INFO - Job 71: Subtask fetch_events
[2023-06-11 03:57:55,857] {task_command.py:371} INFO - Running <TaskInstance: 01_unscheduled.fetch_events manual__2023-06-11T03:54:24.205713+00:00 [running]> on host fd847b0d0eb3
[2023-06-11 03:57:55,898] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=01_unscheduled
AIRFLOW_CTX_TASK_ID=fetch_events
AIRFLOW_CTX_EXECUTION_DATE=2023-06-11T03:54:24.205713+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-11T03:54:24.205713+00:00
[2023-06-11 03:57:55,900] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-11 03:57:55,901] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p /data/events && curl -o /data/events.json https://develop-park.tistory.com/rss']
[2023-06-11 03:57:55,909] {subprocess.py:85} INFO - Output:
[2023-06-11 03:57:55,912] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/data’: Permission denied
[2023-06-11 03:57:55,913] {subprocess.py:96} INFO - Command exited with return code 1
[2023-06-11 03:57:55,924] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-11 03:57:55,927] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=01_unscheduled, task_id=fetch_events, execution_date=20230611T035424, start_date=20230611T035755, end_date=20230611T035755
[2023-06-11 03:57:55,936] {standard_task_runner.py:97} ERROR - Failed to execute job 71 for task fetch_events (Bash command failed. The command returned a non-zero exit code 1.; 650)
[2023-06-11 03:57:55,949] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-11 03:57:55,975] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
